[package]
name = "ferese-theme"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
jiff.workspace = true
ferese-theme-model = { path = "../ferese-theme-model" }
libcosmic = { workspace = true, features = ["a11y"] }

iced_accessibility = { git = "https://github.com/ferese-wm/libcosmic", rev = "8a0d0664b237a2782955aab1890ed8b1d702324e" }

[dev-dependencies]
ferese-config = { path = "../ferese-config" }
