[package]
name = "ferese-theme"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
jiff.workspace = true
ferese-theme-model = { path = "../ferese-theme-model" }
libcosmic = { workspace = true, features = ["a11y"] }

iced_accessibility = { git = "https://github.com/ferese-wm/libcosmic", rev = "50c3b9cf55fd235e76abbe54b2afe446d5819b7e" }

[dev-dependencies]
ferese-config = { path = "../ferese-config" }
