[package]
name = "ferese-theme"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version = "1.95"

[dependencies]
jiff.workspace = true
ferese-config = { path = "../ferese-config" }
libcosmic = { workspace = true, features = ["a11y"] }
ferese-protocols = { path = "../ferese-protocols", default-features = false, features = ["client"] }
wayland-client.workspace = true
ferese-ipc = { path = "../ferese-ipc" }
serde_json.workspace = true
tokio = { version = "1", features = ["rt", "sync", "time"] }

iced_accessibility = { git = "https://github.com/pop-os/libcosmic", rev = "03d7dcb832bc6d15bc1bb07327a1aa426b2d5bc0" }
