[package]
name = "ferese-lock"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
ferese-ipc = { path = "../../crates/ferese-ipc" }
serde_json.workspace = true
ferese-theme = { path = "../../crates/ferese-theme" }
ferese-config = { path = "../../crates/ferese-config" }
libcosmic.workspace = true
jiff.workspace = true
image = { version = "0.25.10", default-features = false }
libc.workspace = true
libloading = "0.8.9"
zeroize = "1.9"
wayland-client.workspace = true
tokio = { version = "1", features = ["rt", "time"] }

[dev-dependencies]
tempfile.workspace = true
