pub struct Preset {
    pub name: &'static str,
    pub description: &'static str,
    pub accent: &'static str,
    pub base: &'static str,
    pub text: &'static str,
    pub muted: &'static str,
    pub border: &'static str,
    pub gradient_end: &'static str,
}

pub const PRESETS: [Preset; 6] = [
    Preset {
        name: "Ferese Blue",
        description: "Default · logo blue",
        accent: "#3D7BE6",
        base: "#111821",
        text: "#F4F7FB",
        muted: "#8793A2",
        border: "#FFFFFF18",
        gradient_end: "#3D7BE6",
    },
    Preset {
        name: "Monochrome",
        description: "Dark · grayscale",
        accent: "#E5E5E5",
        base: "#101012",
        text: "#EDEDF0",
        muted: "#97979F",
        border: "#FFFFFF18",
        gradient_end: "#696973",
    },
    Preset {
        name: "Gruvbox",
        description: "Dark · warm orange",
        accent: "#FE8019",
        base: "#282828",
        text: "#EBDBB2",
        muted: "#BDAE93",
        border: "#504945",
        gradient_end: "#FABD2F",
    },
    Preset {
        name: "Dracula",
        description: "Dark · purple",
        accent: "#BD93F9",
        base: "#282A36",
        text: "#F8F8F2",
        muted: "#A4ADCD",
        border: "#44475A",
        gradient_end: "#FF79C6",
    },
    Preset {
        name: "Ayu Light",
        description: "Light · paper",
        accent: "#8F5300",
        base: "#F8F9FA",
        text: "#5C6166",
        muted: "#596574",
        border: "#C8CDD3",
        gradient_end: "#996000",
    },
    Preset {
        name: "Monokai",
        description: "Dark · warm green",
        accent: "#A6E22E",
        base: "#272822",
        text: "#F8F8F2",
        muted: "#B2B29F",
        border: "#414339",
        gradient_end: "#E6DB74",
    },
];
