[package]
name = "ferese"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
ferese-animation = { path = "../crates/ferese-animation" }
ferese-core = { path = "../crates/ferese-core" }
ferese-layout = { path = "../crates/ferese-layout" }
libc.workspace = true
smithay.workspace = true
serde.workspace = true
toml.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
xcursor.workspace = true
