[package]
name = "ferese"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
ab_glyph = "0.2.32"
fontdb = "0.23.0"
calloop.workspace = true
ferese-animation = { path = "../crates/ferese-animation" }
ferese-core = { path = "../crates/ferese-core" }
ferese-ipc = { path = "../crates/ferese-ipc" }
ferese-layout = { path = "../crates/ferese-layout" }
ferese-protocols = { path = "../crates/ferese-protocols", features = ["server"] }
libc.workspace = true
image = { version = "0.25.10", default-features = false, features = ["png", "jpeg", "webp"] }
smithay.workspace = true
serde.workspace = true
serde_json.workspace = true
toml.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
xcursor.workspace = true
