[preferred]
default=gtk;
org.freedesktop.impl.portal.ScreenCast=ferese;
org.freedesktop.impl.portal.Settings=ferese;
org.freedesktop.impl.portal.Screenshot=ferese;
org.freedesktop.impl.portal.Wallpaper=ferese;
