[preferred]
default=gtk;
org.freedesktop.impl.portal.ScreenCast=ferese;
org.freedesktop.impl.portal.Settings=ferese;
org.freedesktop.impl.portal.Screenshot=ferese;
org.freedesktop.impl.portal.Wallpaper=ferese;
org.freedesktop.impl.portal.Background=ferese;
org.freedesktop.impl.portal.Usb=ferese;
org.freedesktop.impl.portal.Lockdown=ferese;
org.freedesktop.impl.portal.GlobalShortcuts=ferese;
org.freedesktop.impl.portal.Inhibit=ferese;
