[package]
name = "ferese-polkit-agent"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
ferese-config = { path = "../../crates/ferese-config" }
ferese-theme = { path = "../../crates/ferese-theme" }
glib = "0.21.5"
libc.workspace = true
libcosmic = { workspace = true, features = ["wgpu"] }
libloading = "0.8.9"
serde.workspace = true
serde_json.workspace = true
tokio = { version = "1", features = ["rt-multi-thread", "macros", "sync", "time"] }
zbus = "5.19.0"
zeroize = "1.9"
